In [7]:
########## 1 Import libraries for database access and data handling
import sqlite3
import pandas as pd

# Connect to the SQLite IMDb database
conn = sqlite3.connect("imdb_data.db")

In [8]:
########## 2 List tables in the SQLite database
tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
    conn
)

tables

                name
0       actors_pivot
1    actresses_pivot
2    directors_pivot
3    filtered_movies
4        name_basics
5         title_akas
6       title_basics
7         title_crew
8      title_episode
9   title_principals
10     title_ratings

In [9]:
########## 3 Preview title_basics
pd.read_sql("SELECT * FROM title_basics LIMIT 5;", conn)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894.0,None,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892.0,None,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892.0,None,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892.0,None,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893.0,None,1,Short

In [10]:
########## 4 Preview title_ratings
pd.read_sql("SELECT * FROM title_ratings LIMIT 5;", conn)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2188
1  tt0000002            5.5       307
2  tt0000003            6.4      2274
3  tt0000004            5.1       197
4  tt0000005            6.2      3012

In [11]:
########## 5 Preview title_principals
pd.read_sql("SELECT * FROM title_principals LIMIT 5;", conn)

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,None,"[""Self""]"
1,tt0000001,2,nm0005690,director,None,None
2,tt0000001,3,nm0005690,producer,producer,None
3,tt0000001,4,nm0374658,cinematographer,director of photography,None
4,tt0000002,1,nm0721526,director,None,None

In [12]:
########## 6 Preview analytical dataset used for modeling
pd.read_sql("SELECT * FROM filtered_movies LIMIT 5;", conn)

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0004972,The Birth of a Nation,The Birth of a Nation,1915.0,195,"Drama,War",6.1,27935
1,tt0006206,Les Vampires,Les vampires,1915.0,421,"Action,Adventure,Crime",7.3,5798
2,tt0006864,Intolerance,Intolerance: Love's Struggle Throughout the Ages,1916.0,163,"Drama,History",7.7,17708
3,tt0009968,Broken Blossoms,Broken Blossoms or The Yellow Man and the Girl,1919.0,90,"Drama,Romance",7.2,11651
4,tt0010323,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,1920.0,67,"Horror,Mystery,Thriller",8.0,75092